# Generated by Django 6.1 on 2026-08-19 05:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def make_body_json(apps, schema_editor):
    HomePage = apps.get_model('home', 'HomePage')
    HomePage.objects.filter(body="").update(body="[]")

    StandardPage = apps.get_model('home', 'StandardPage')
    StandardPage.objects.filter(body="").update(body="[]")


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_govtorderindexpage_newsindexpage_noticeindexpage_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHTMLPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('raw_html', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Raw HTML'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HeaderFooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_header_html', models.TextField(blank=True, help_text='Raw HTML injected in the header (overrides standard header if supplied).', verbose_name='Custom Header HTML')),
                ('custom_footer_html', models.TextField(blank=True, help_text='Raw HTML injected in the footer (overrides standard footer if supplied).', verbose_name='Custom Footer HTML')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(make_body_json),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('raw_html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Raw HTML'})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('raw_html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Raw HTML'})}),
        ),
    ]
