# Generated by Django 6.1 on 2026-08-19 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_menu_headerfootersettings_additional_css_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent menu item if this is a submenu item (supports up to 3 levels).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.menuitem', verbose_name='Parent Menu Item'),
        ),
    ]
