# Generated by Django 6.1 on 2026-08-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_customhtmlpage_body_alter_homepage_body_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfootersettings',
            name='copyright_text',
            field=models.CharField(default='Department of Public Administration. All rights reserved.', max_length=255, verbose_name='Copyright Text'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='footer_about_text',
            field=models.TextField(blank=True, default='This is the official content management portal for disseminating public orders, notices, news, and official announcements. Designed to ensure transparency.', verbose_name='Footer About Text'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='footer_about_title',
            field=models.CharField(default='GovCMS Portal', max_length=255, verbose_name='Footer Section Title'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='footer_address',
            field=models.CharField(default='Secretariat Complex, Block A', max_length=255, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='footer_email',
            field=models.EmailField(default='support-govsite@example.com', max_length=254, verbose_name='Support Email'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='footer_phone',
            field=models.CharField(default='+11-2345-6789', max_length=50, verbose_name='Support Phone'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Upload/Select your logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Site Logo'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='site_subtitle',
            field=models.CharField(default='Government Content Management System Portal', max_length=255, verbose_name='Site Subtitle'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='site_title',
            field=models.CharField(default='DEPARTMENT OF PUBLIC ADMINISTRATION', max_length=255, verbose_name='Site Title'),
        ),
    ]
