# Generated by Django 6.1 on 2026-08-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_headerfootersettings_copyright_text_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfootersettings',
            name='header_css',
            field=models.TextField(blank=True, help_text='Write custom CSS rules specifically for the header section.', verbose_name='Header CSS Customization'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='header_js',
            field=models.TextField(blank=True, help_text='Write custom JavaScript behaviors for the header section.', verbose_name='Header JS Customization'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='right_logo',
            field=models.ForeignKey(blank=True, help_text='Upload/Select an optional right-side logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Right Site Logo'),
        ),
        migrations.AlterField(
            model_name='headerfootersettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Upload/Select your main left logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Left Site Logo'),
        ),
        migrations.CreateModel(
            name='AdminBrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_css', models.TextField(blank=True, help_text='Write custom CSS rules to beautify the admin dashboard.', verbose_name='Custom CSS Styles')),
                ('custom_js', models.TextField(blank=True, help_text='Write custom JavaScript behaviors for the admin dashboard.', verbose_name='Custom JS Script')),
                ('logo_left', models.ForeignKey(blank=True, help_text='Upload/Select logo for the left side of the Wagtail admin sidebar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Admin Left Logo')),
                ('logo_right', models.ForeignKey(blank=True, help_text='Upload/Select logo for the right side of the Wagtail admin header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Admin Right Logo (Optional)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
