# Generated by Django 6.1 on 2026-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_headerfootersettings_header_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfootersettings',
            name='site_title_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site Title Line 1 (e.g. Hindi)'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='site_title_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site Title Line 2 (e.g. English Main)'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='site_title_line_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site Title Line 3 (e.g. Urdu)'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='site_title_line_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Site Title Line 4 (e.g. Subtitle)'),
        ),
    ]
