# Generated by Django 6.0.8 on 2026-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_customhtmlpage_body_alter_downloadspage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='category',
            field=models.CharField(blank=True, default='general', help_text="Filter key/category to identify where this download belongs (e.g. 'general', 'reports', 'circulars'). Default is 'general'.", max_length=100, verbose_name='Category / Key'),
        ),
        migrations.AddField(
            model_name='downloadspage',
            name='category_filter',
            field=models.CharField(blank=True, default='general', help_text="Filter to list only downloads matching this category key (e.g. 'general', 'reports'). Leave blank to show all.", max_length=100, verbose_name='Category / Key Filter'),
        ),
    ]
