# Generated by Django 6.0.8 on 2026-09-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_download_category_downloadspage_category_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadspage',
            name='category_filter',
            field=models.CharField(blank=True, default='', help_text="Optional category key to filter downloads. If left blank, it automatically matches downloads matching this page's title or slug (e.g. 'Guidelines'). Type 'all' to show every download.", max_length=100, verbose_name='Category / Key Filter'),
        ),
    ]
