# Generated by Django 6.0.8 on 2026-09-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_downloadspage_category_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional short description or subtitle for this document', max_length=255, verbose_name='Subtitle / Short Description'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent menu item if this is a submenu item (supports up to 5 levels).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.menuitem', verbose_name='Parent Menu Item'),
        ),
    ]
