# Generated by Django 6.0.8 on 2026-09-01 11:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_formfield_field_type'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or name of this record', max_length=255)),
                ('category', models.CharField(default='general', help_text='Category / Group Key (e.g. Tenders, Staff Directory, Projects, FAQs, Schemes)', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or reference number', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_fields', wagtail.fields.StreamField([('attribute', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Closing Date, EMD Amount, Designation, Budget', 'label': 'Field Name'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Field Value'}), 2: ('wagtail.blocks.StructBlock', [[('field_name', 0), ('field_value', 1)]], {})}, help_text='Add dynamic custom fields specific to this record')),
                ('document', models.ForeignKey(blank=True, help_text='Optional PDF or file attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Custom Data Record',
                'verbose_name_plural': 'Custom Data Records',
            },
        ),
    ]
