# Generated by Django 6.0.8 on 2026-09-03 06:51

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_customdatarecord_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadspage',
            name='category_select',
            field=models.CharField(blank=True, choices=home.models.get_download_categories, default='', help_text='Select a category from the dropdown (automatically populated from your Portal Content ➔ Downloads snippets).', max_length=100, verbose_name='Select Category from Existing Downloads'),
        ),
        migrations.AlterField(
            model_name='downloadspage',
            name='category_filter',
            field=models.CharField(blank=True, default='', help_text="Optional: Type category name manually if not in dropdown or to filter by custom keyword. Type 'all' to show every download.", max_length=100, verbose_name='Or Type Custom Category Filter'),
        ),
    ]
