# Generated by Django 6.0.8 on 2026-09-03 07:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_downloadspage_category_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdatarecord',
            name='extra_fields',
            field=wagtail.fields.StreamField([('attribute', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Closing Date, EMD Amount, Email, Designation, Budget, Phone', 'label': 'Field Name / Column Header'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text (Normal string)'), ('number', 'Numerical (Numbers / Currency / Count)'), ('date', 'Date / Deadline'), ('email', 'Email Address (Clickable mailto link)'), ('url', 'Website / Link URL (Clickable link)'), ('phone', 'Phone / Mobile Number (Clickable tel link)')], 'help_text': 'Select input data type for formatting and interactive links', 'label': 'Field Type / Input Type'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Field Value'}), 3: ('wagtail.blocks.StructBlock', [[('field_name', 0), ('field_type', 1), ('field_value', 2)]], {})}, help_text='Add dynamic custom fields specific to this record'),
        ),
    ]
