# Generated by Django 6.0.8 on 2026-09-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_headerfootersettings_enable_header_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfootersettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='e.g. https://facebook.com/nhm', verbose_name='Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='e.g. https://instagram.com/nhm', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='e.g. https://linkedin.com/company/nhm', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='topbar_feedmap_text',
            field=models.CharField(blank=True, default='Feedmap', max_length=100, verbose_name='Feedmap Link Text'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='topbar_feedmap_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Feedmap Link URL (Optional)'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='twitter_url',
            field=models.URLField(blank=True, default='', help_text='e.g. https://twitter.com/nhm', verbose_name='Twitter / X URL'),
        ),
        migrations.AddField(
            model_name='headerfootersettings',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text='e.g. https://youtube.com/@nhm', verbose_name='YouTube Channel URL'),
        ),
    ]
