# Generated by Django 6.0.8 on 2026-09-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_headerfootersettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_theme', models.CharField(choices=[('saffron_navy', '🟠 Saffron & Navy Blue (Official Portal - Default)'), ('royal_blue', '🔵 Royal Government Blue & Gold'), ('emerald_green', '🟢 Emerald Health & Forest Green'), ('digital_slate', '🟣 Digital Indigo & Slate Teal'), ('maroon_gold', '🔴 Heritage Maroon & Gold'), ('clean_light', '⚪ Clean Minimalist Light Slate'), ('custom', '🎨 Custom Colors (Configured Below)')], default='saffron_navy', help_text='Select a pre-designed government theme preset. All colors across the portal will instantly update.', max_length=50, verbose_name='Active Theme Preset')),
                ('custom_primary', models.CharField(blank=True, default='', help_text='e.g. #003366', max_length=20, verbose_name='Custom Primary Color')),
                ('custom_secondary', models.CharField(blank=True, default='', help_text='e.g. #f39c12', max_length=20, verbose_name='Custom Secondary / Accent Color')),
                ('custom_navbar_bg', models.CharField(blank=True, default='', help_text='e.g. #003366', max_length=20, verbose_name='Custom Navbar Background')),
                ('custom_navbar_text', models.CharField(blank=True, default='', help_text='e.g. #ffffff', max_length=20, verbose_name='Custom Navbar Text Color')),
                ('custom_card_header_bg', models.CharField(blank=True, default='', help_text='e.g. #f39c12', max_length=20, verbose_name='Custom Card / Table Header Color')),
                ('custom_card_header_text', models.CharField(blank=True, default='', help_text='e.g. #000000', max_length=20, verbose_name='Custom Header Text Color')),
                ('custom_footer_bg', models.CharField(blank=True, default='', help_text='e.g. #111827', max_length=20, verbose_name='Custom Footer Background')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
