# Generated by Django 6.0.8 on 2026-09-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_headerfootersettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhtmlpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='downloadspage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='formpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='govtorderindexpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='govtorderpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='newspage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='noticeindexpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='noticepage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='programimplementationplanpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='rtipage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='theme',
            field=models.CharField(choices=[('modern_minimal', 'Modern Minimal'), ('corporate_professional', 'Corporate Professional'), ('dark_creative', 'Dark Creative')], default='modern_minimal', help_text='Select the visual theme for this page while keeping the content unchanged.', max_length=40),
        ),
    ]
